src/Entity/Tricks.php
<?php
namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\TricksRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Tricks
{
    /********** ATTRIBUTS **********/
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * Nom de la figure
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;
    /**
     * La description de la figure
     * @ORM\Column(type="text")
     */
    private $description;
    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="tricks", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $images;

    /**
     * @var
     */
    private $imageFile;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MediaVideo", mappedBy="trick", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $mediaVideos;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="tricks", cascade={"persist", "remove"} )
     */
    private $comments;
    /**
     * Date de la creation de la figure
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;
    /**
     * Le groupe de la figure
     * @ORM\Column(type="string", length=255)
     */
    private $groupe;
    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;
    /********** CONSTRUCTOR **********/
    public function __construct()
    {
        $this->date = new \Datetime();
        $this->comments = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->mediaVideos = new ArrayCollection();
    }
    /********** GETTERS & SETTERS **********/
    /**
     * @param string $images
     */
    public function setImages(string $images): void
    {
        $this->images = $images;

    }
    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }
    /**
     * @param mixed $imageFile
     */
    public function setImageFile($imageFile): void
    {
        $this->imageFile = $imageFile;
    }
    /**
     * @return Collection
     */
    public function getImages(): Collection
    {
        return $this->images;
    }
    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
    /**
     * @param mixed $updatedAt
     */
    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }
    /**
     * @return Collection|Comment[]
     */
    public function getComments()
    {
        return $this->comments;
    }
    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }
    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }
    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }
    /**
     * @return mixed
     */
    public function getGroupe()
    {
        return $this->groupe;
    }
    /**
     * @param mixed $groupe
     */
    public function setGroupe($groupe)
    {
        $this->groupe = $groupe;
    }
    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }
    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }
    /**
     * @return Collection|MediaVideo[]
     */
    public function getMediaVideos(): Collection
    {
        return $this->mediaVideos;
    }
    /********** AUTRES METHODES **********/
    /**
     * @ORM\PreUpdate
     */
    public function updateDate()
    {
        $this->setUpdatedAt(new \Datetime());
    }

    /**
     * @param Image $image
     * @return Tricks
     */
    public function addImage(Image $image): self
    {
        $this->images->add($image);
        $image->setTricks($this);
        return $this;
    }

    /**
     * @param Image $image
     * @return $this
     */
    public function removeImage(Image $image)
    {
        $this->images->removeElement($image);
        return $this;
    }

    /**
     * @param MediaVideo $mediaVideo
     * @return Tricks
     */
    public function addMediaVideo(MediaVideo $mediaVideo): self
    {
        if (!$this->mediaVideos->contains($mediaVideo)) {
            $this->mediaVideos[] = $mediaVideo;
            $mediaVideo->setTrick($this);
        }
        return $this;
    }

    /**
     * @param MediaVideo $mediaVideo
     * @return Tricks
     */
    public function removeMediaVideo(MediaVideo $mediaVideo): self
    {
        if ($this->mediaVideos->contains($mediaVideo)) {
            $this->mediaVideos->removeElement($mediaVideo);
            // set the owning side to null (unless already changed)
            if ($mediaVideo->getTrick() === $this) {
                $mediaVideo->setTrick(null);
            }
        }
        return $this;
    }
    // Vérification si il y a une image attachée à la figure

    /**
     * @return bool
     */
    public function hasImages(){
        if ($this->getImages()->isEmpty()){
            return false;
        }
            else{
                return true;
            }
        }

    /**
     * @return bool
     */
    public function hasVideos(){
        if ($this->getMediaVideos()->isEmpty()){
            return false;
        }
        }


    /**
     * Pour image a affichée sur le show - la fonction renvoi soit la première image soit l'image par defaut
     * @return string
     */
    public function getCoverPath(){
        if ($this->getImages()->isEmpty()){
            return 'img/bg.jpg';
        }
       
    }
}

src/Controller/TricksController.php
<?php

namespace App\Controller;

use App\Repository\TricksRepository;
use App\Entity\MediaVideo;
use App\Entity\Comment;
use App\Entity\Image;
use App\Entity\Tricks;
use App\Form\CommentEditType;
use App\Form\CommentType;
use App\Form\TricksType;
use App\Form\TricksEditType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;


/**
 * @property TokenStorageInterface tokenStorage
 * @property TricksRepository trickRepo
 */
class TricksController extends AbstractController
{

    /**
     * @var TricksRepository
     */
    private $trickRepo;
    /**
     * @var TokenStorageInterface
     */
    private $tokenStorage;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;


    // CONSTRUCTEUR //

    /**
     * TricksController constructor.
     * @param TricksRepository $trickRepo
     * @param EntityManagerInterface $entityManager
     * @param TokenStorageInterface $tokenStorage
     */
    public function __construct(
        TricksRepository $trickRepo, // Récupère le répository de Tricks.
        EntityManagerInterface $entityManager, // Gère les relations entre entités, sauvegarde & extrait les données de la base.
        TokenStorageInterface $tokenStorage // L'interface pour les informations d'authentification de l'utilisateur.
    )
    {
        $this->tokenStorage = $tokenStorage;
        $this->entityManager = $entityManager;
        $this->trickRepo = $trickRepo;
    }

     ///////////////////////////////////////////////
    /// AFFICHER UNE LISTE DE FIGURES | ACCUEIL ///
   ///////////////////////////////////////////////

    /**
     * @Route("/", name="homepage")
     */
    public function homepage()
    {
        // $tricks stock toutes les figures récupérées par la variable $trickRepo
        $tricks = $this->trickRepo->findAll();

        return $this->render('index.html.twig',  array('tricks' => $tricks));
    }

     ///////////////////////////
    /// AFFICHER UNE FIGURE ///
   ///////////////////////////

    /**
     * @Route("/figure/{id}", name="show")
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function show(Request $request ,$id)
    {
        // $tricks stock toutes les figures récupérées par la variable $trickRepo
        $trick = $this->trickRepo->find($id);

        if (!$trick) {
            throw new NotFoundHttpException( 'Aucun résultat ne correspond à votre recherche' );
        }
        /*
         *  Nouvelle instance de l'objet Comment stocké dans $comment
         *  La methode setTricks lie le commentaire à la figure
         *  La variable $form stock le formulaire créé à partir de CommentType
         */
        $comment = new Comment();
        $comment->setTricks($trick);
        $form = $this->get('form.factory')->create(CommentType::class, $comment);

        /*
         *  isMethod() vérifie si la requete est en méthode POST
         *  handleRequest() récupére les valeurs des champs dans les inputs du formulaire
         *  isValide() valide les données saisies
         */
        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            /*
             * la variable $comment récupère l'utilisateur connécté avec setAuthor() par son token
             * (persist) Demande au gestionnaire d'entités(entityManager) de suivre les modifications apportées à l'objet
             * (flush) Pousse les modifications des objets d’entités qu’il suit dans la base de données en une seule transaction
             */
            $comment->setAuthor($this->tokenStorage->getToken()->getUser());
            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            return $this->redirectToRoute('show', array('id' => $trick->getId($id)));
        }
        return $this->render('trick/show/show.html.twig', array('trick' => $trick,  'form' => $form->createView(), 'id' => $trick->getId($id), 'comment' => $comment));
    }

     //////////////////////////
    /// AJOUTER UNE FIGURE ///
   //////////////////////////

    /**
     * @Route("/ajout", name="add")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function add(Request $request)
    {
        /*
         * $trick stock la nouvelle instance de l'objet Tricks
         * $form stock le nouveau formulaire créé avec createForm() via TricksType
         * handleRequest() récupére les valeurs des champs dans les inputs du formulaire via la variable $request
         */
        $trick = new Tricks();
        $form   = $this->createForm(TricksType::class, $trick);
        $form->handleRequest($request);
        /*
        *  isMethod() vérifie si la requete est en méthode POST
        *  isValide valide les données saisies
        */
        if ($form->isSubmitted() && $form->isValid()){
            /*
             * (em) recupère $entityManager pour gerer l'entrer des informations dans la base de donnée
             * (persist) Demande au gestionnaire d'entités(entityManager) de suivre les modifications apportées à l'objet
             * (flush) Pousse les modifications des objets d’entités qu’il suit dans la base de données en une seule transaction
             */
            $em = $this->entityManager;
            $em->persist($trick);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');

            return $this->redirectToRoute('show', array('id' => $trick->getId(), 'trick' => $trick));
        }
        return $this->render('trick/add/add.html.twig', array(
            'form' => $form->createView()));
    }

     /////////////////////////
    /// EDITER UNE FIGURE ///
   /////////////////////////

    /**
     * @Route("/editer/{id}", name="edit")
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function edit( $id, Request $request)
    {
        // $trick stock toutes les figures récupérées par la variable $trickRepo
        $trick = $this->trickRepo->find($id);

        if (null === $trick) {
            throw new NotFoundHttpException("Cette page n'existe pas");}


        $form = $this->createForm(TricksEditType::class, $trick);
        $form->handleRequest($request);

        /*
        *   isSubmitted() vérifie si le formulaire est soumis
        *  isValide valide les données saisies
        */
        if ($form->isSubmitted() && $form->isValid()) {

            /*
            * (persist) Demande au gestionnaire d'entités(entityManager) de suivre les modifications apportées à l'objet
            * (flush) Pousse les modifications des objets d’entités qu’il suit dans la base de données en une seule transaction
            */
            $this->entityManager->persist($trick);
            $this->entityManager->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée.');

            return $this->redirectToRoute('show', array('id' => $trick->getId()));
        }
        return $this->render('trick/edit/edit.html.twig', array(
            'trick' => $trick,
            'form'   => $form->createView(),
        ));
    }

     ////////////////////////////
    /// SUPPRIMER UNE FIGURE ///
   ////////////////////////////

    /**
     * @Route("/supprimer/{id}", name="delete")
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function delete($id)
    {
        /*
         * (em) stock le gestionnaire d'entités (entityManager)
         * (tricks) stock la liste des figure récupérées avec getRepositoty()
         */
        $em = $this->entityManager;
        $tricks = $em->getRepository(Tricks::class)->find($id);

        if (null === $tricks) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }
        /*
        *  remove vas supprimer la figure de la base de donnée à l'aide entityManager stocké dans (em)
        *  (flush) Pousse les modifications des objets d’entités qu’il suit dans la base de données en une seule transaction
        */
        $em->remove($tricks);
        $em->flush();

        return $this->redirectToRoute('homepage');
    }


    /// SUPPRIMER UNE IMAGE ///
    /**
     * @Route("/supprimerImage/{id}", name="deleteImage")
     * @param Image $image
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteImage(Image $image, Request $request){
        if (null === $image) {
            throw new NotFoundHttpException("Imposible de supprimer la vidéo.");
        }
        $em = $this->entityManager;
        $em->remove($image);
        $em->flush();
        $request->getSession()->getFlashBag()->add('notice', 'L\'image a bien été supprimée.');
        return $this->redirectToRoute('show', ['id' => $image->getTricks()->getId()]);
    }


    /// SUPPRIMER UNE VIDEO ///

    /**
     * @Route("/supprimerVideo/{id}", name="deleteVideo")
     * @param MediaVideo $mediaVideo
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteVideo(MediaVideo $mediaVideo, Request $request){

        if (null === $mediaVideo) {
            throw new NotFoundHttpException("Imposible de trouver la vidéo.");
        }
        $em = $this->entityManager;
        $em->remove($mediaVideo);
        $em->flush();

templates/trick/show/show-base.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<section class="page-section about-heading">
    <div class="container">
        <div class="row  p-5" id="box-search">
            <div class="sm-faded rounded center-block col-lg-6">
                <div>
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Figure</span>
                        <span class="titre section-heading-lower">{{ trick.name }}</span>
                    </h2>
                </div>
                <div class="thumbnail text-center first-image-container center-block col-lg-10 ">
                    <img class="img-responsive thumbnail text-center img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{{asset(trick.coverPath)}}" alt=""/>
                </div>
            </div>
        </div>
        <div class="about-heading-content">
            <div class="row">
                <div class="col-xl-10 col-lg-11 mx-auto">
                    <div class="bg-faded rounded p-5">
                        {# Bouton d'édition visible uniquement aux inscrits #}
                        {% if is_granted('ROLE_USER') %}
                            <div class="row pull-right" role="group" >
                                <div><a href="{{ path('edit', {'id': trick.id}) }}" > <i class="fa fa-pencil" aria-hidden="true"></i></a></div>
                                <div><a href="{{ path('delete', {'id': trick.id}) }}" > <i class="fa fa-trash-o" aria-hidden="true"></i></a></div>
                            </div>
                        {% endif %}
                        <div class="album">
                            <div class="container ">

                            {% block show_content %}{% endblock %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('vendor/js/petit_ecran_media.js') }}"></script>
{% endblock %}

templates/trick/show/show-description-tag.html.twig
<div class="row jumbotron text-center description">
    <div>{{ trick.description }}</div>
</div>
<div class="row section-heading mb-4 text-center center-div ">
    <div class="col-lg-12 label-div">
        <span class="col-lg-4 badge badge-primary">{{ trick.groupe }}</span>
        <span class="col-lg-4 badge badge-success">Créé le {{ trick.date|date("d/m/Y") }}</span>
        {% if trick.updatedAt == true %}
            <span class="col-lg-4 badge badge-warning">Modifié le {{ trick.updatedAt|date("d/m/Y") }}</span>
        {% else %}
            <span class="col-lg-4 badge badge-warning">Aucune modification</span>
        {% endif %}
    </div>
</div>

templates/trick/show/show-image-affiche-grand.html.twig
{% if trick.hasImages  %}{# Si elles existents #}
    <h1 class="media-grand-ecran">Images</h1>
    <div class="row jumbotron media-grand-ecran">
        {# AFFICHAGE IMAGES #}
        {% for image in trick.images %}
            <div class="petite col-lg-4 media center-block marge">
                <div class="row marge">
                    <div class=" col-12">
                        <a href="{{ asset('uploads/'~image.path) }}" data-lightbox="roadtrip">
                            <img class="marge" src="{{ asset('uploads/'~image.path) }}"/></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/trick/show/show-image-affiche-petit.html.twig
{% if trick.hasImages  %}{# Si images éxistants #}
    <div class="container media-petit-ecran">
        <div class="panel panel-default">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row toggle" id="dropdown-detail-1" data-toggle="detail-1">
                        <div class="col-xs-10">Images</div>
                        <div class="col-xs-2"><i class="fa fa-chevron-down pull-right"></i></div>
                    </div>
                    <div id="detail-1">
                        <div class="container">
                            <div class="fluid-row">
                                <div class="col-xs-5">
                                    {# Liste images #}
                                    {% for image in trick.images %}
                                        <div class="petite col-lg-4 media center-block marge">
                                            <div class="row marge">
                                                <div class=" col-12">
                                                    <a href="{{ asset('uploads/'~image.path) }}" data-lightbox="roadtrip">
                                                        <img class="marge" src="{{ asset('uploads/'~image.path) }}"/></a>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endif %}

templates/trick/show/show-video-affiche-grand.html.twig
{% if trick.mediaVideos  %}{# Si videos existent #}
    <h1 class="media-grand-ecran">Videos</h1>
    <div class="row jumbotron media-grand-ecran">
        {% for video in trick.mediaVideos if video.id %}
            <div class="petite col-lg-4 media center-block ">
                <div class="row">
                    <div class="col-12 marge">
                        {{ video.video|raw }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/trick/show/show-video-affiche-petit.html.twig
{% if trick.hasVideos  %}{# Si elles existents #}
    <div class="container media-petit-ecran">
        <div class="panel panel-default">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row toggle" id="dropdown-detail-2" data-toggle="detail-2">
                        <div class="col-xs-10">
                            Videos
                        </div>
                        <div class="col-xs-2"><i class="fa fa-chevron-down pull-right"></i></div>
                    </div>
                    <div id="detail-2">
                        <div class="container">
                            <div class="fluid-row">
                                <div class="col-xs-5">
                                    {# Liste videos #}
                                    {% for video in trick.mediaVideos %}
                                        <div class="petite col-lg-4 media center-block ">
                                            <div class="row">
                                                <div class="col-12 marge">
                                                    {{ video.video|raw }}
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endif %}

templates/trick/show/show.html.twig
{% extends 'trick/show/show-base.html.twig' %}

{% block show_content %}
    {% include 'trick/show/show-image-affiche-petit.html.twig' %}{# AFFICHAGE DES IMAGES - PETIT ECRAN #}
    {% include 'trick/show/show-video-affiche-petit.html.twig' %}{# AFFICHAGE DES VIDEOS - PETIT ECRAN #}
    {% include 'trick/show/show-image-affiche-grand.html.twig' %}{# AFFICHAGE DES IMAGES - GRAND ECRAN #}
    {% include 'trick/show/show-video-affiche-grand.html.twig' %}{# AFFICHAGE DES VIDEOS - GRAND ECRAN #}
    {% include 'trick/show/show-description-tag.html.twig' %}{# DESCRIPTION & TAGS #}
    {% include 'comment/commentaire.html.twig' %}{# COMMENTAIRES #}
{% endblock %}